import Head from "next/head";
import Image from "next/image";

import type { NextPage } from "next";

const Home: NextPage = () => (
  <div>
    <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>

    <header>
      <h1>My Image Gallery</h1>
    </header>

    <main className="gallery">
      <ul id="nav" className="nav" />

      <figure className="preview">
        <Image
          id="preview-img"
          // src="/vercel.svg"
          alt="Preview"
          // width={72}
          // height={16}
        />

        <input id="preview-title" className="preview--title" type="text" />
      </figure>
    </main>

    <footer>
      <p>
        Built with ❤️ by
        <a href="https://github.com/relaxxpls">
          <b>Laxman Desai</b>
        </a>
      </p>
    </footer>
  </div>
);

export default Home;
