import Head from "next/head";
// import Image from "next/image";

import type { NextPage } from "next";

const Home: NextPage = () => (
  <div>
    <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
  </div>
);

export default Home;
